### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by ZhaoXiangXML** [h3nnn4n/Rust-TypeScript-Wasm-Template#13]
I'm trying to run this project on Windows, steps 1 to 9 works fine, I can see it running in browser.

However I cannot run the tests, I go the following error:

```
yarn run test-server
yarn run v1.22.18
$ webpack-dev-server --config webpack-test.config.js
[webpack-cli] Failed to load 'C:\Projects\motphys\motphys-sdk-javascript\webpack-test.config.js' config
[webpack-cli] Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] should be an object:
   object { patterns, options? }
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ZhaoXiangXML** [comment]
I'm trying to fix this issue and this is my progress so far:

package.json:
```json
{
  "name": "rust-wasm-template",
  "version": "0.1.0",
  "description": "A base template with rust, wasm-bindgen, webpack, mocha and babel",
  "main": "index.js",
  "scripts": {
    "build": "webpack --config webpack.config.js",
    "dev-server": "webpack-dev-server --config webpack.config.js",
    "test-server": "webpack-dev-server --config webpack-test.config.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/h3nnn4n/Rust-Wasm-Template"
  },
  "keywords": [
    "webassembly",
    "wasm",
    "rust",
    "webpack"
  ],
  "author": "Renan S Silva (h3nnn4n) <uber.renan@gmail.com>",
  "homepage": "https://github.com/h3nnn4n/Rust-Wasm-Template",
  "devDependencies": {
    "@babel/core": "^7.15.8",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/preset-env": "^7.15.8",
    "@types/jquery": "^3.5.7",
    "babel-loader": "^8.2.2",
    "chai": "^4.3.4",
    "copy-webpack-plugin": "^9.0.1",
    "detect-mocha": "^0.1.0",
    "eslint": "^8.0.1",
    "hello-wasm-pack": "^0.1.0",
    "mocha": "^9.1.2",
    "mocha-loader": "^5.1.5",
    "sinon": "^11.1.2",
    "ts-loader": "^9.2.6",
    "typescript": "^4.4.4",
    "webpack": "^5.58.2",
    "webpack-cli": "^4.9.0",
    "webpack-dev-server": "^4.3.1",
    "yarn-upgrade-all": "^0.5.4"
  },
  "dependencies": {
    "@popperjs/core": "^2.10.2",
    "bootstrap": "^5.1.3",
    "es6-promise": "^4.2.8",
    "jquery": "^3.6.0",
    "sprintf-js": "^1.1.2",
    "tslib": "^2.3.1",
    "stream": "^0.0.2",
    "stream-browserify": "^3.0.0",
    "util": "^0.12.4"
  }
}

```
webpack-test.config.js:
```javascript
const CopyWebpackPlugin = require("copy-webpack-plugin");
const path = require('path');
const glob = require("glob");

module.exports = {
  stats: {
    errorDetails: true
  },
  entry: [].concat.apply([], [
    './spec/runner.js',
  ]),
  output: {
    path: path.resolve(__dirname, "test-dist"),
    filename: "test_index.js",
  },
  target: 'web',
  mode: "development",
  plugins: [
    new CopyWebpackPlugin({
      patterns: [
        { from: "test.html", to: "test.html" },
      ]
    }
    )
  ],
  resolve: {
    extensions: [".js", ".ts", '.wasm'],
    fallback: {
      "util": require.resolve("util/"),
      "stream": require.resolve("stream-browserify")
    }
  },
  experiments: { asyncWebAssembly: true },
  module: {
    rules: [{
      include: [
        path.resolve(__dirname, "js")
      ],
    },
    {
      test: /\.js$/,
      exclude: ["/node_modules/"],
      use: {
        loader: 'babel-loader',
        options: {
          presets: ['@babel/preset-env'],
          plugins: ['@babel/plugin-syntax-dynamic-import']
        }
      }
    },
    {
      test: /spec\.js$/,
      use: 'mocha-loader',
      exclude: /node_modules/
    }
    ]
  }
};

```

and this is the current error message:
```
WARNING in ./node_modules/mocha/lib/mocha.js 391:24-53
Critical dependency: the request of a dependency is an expression
    at RequireResolveContextDependency.getWarnings (C:\Projects\test\Rust-TypeScript-Wasm-Template-master\node_modules\webpack\lib\dependencies\ContextDependency.js:102:18)        
    at Compilation.reportDependencyErrorsAndWarnings (C:\Projects\test\Rust-TypeScript-Wasm-Template-master\node_modules\webpack\lib\Compilation.js:3132:24)
    at C:\Projects\test\Rust-TypeScript-Wasm-Template-master\node_modules\webpack\lib\Compilation.js:2729:28
    at eval (eval at create (C:\Projects\test\Rust-TypeScript-Wasm-Template-master\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:29:1)
    at C:\Projects\test\Rust-TypeScript-Wasm-Template-master\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:385:11
    at C:\Projects\test\Rust-TypeScript-Wasm-Template-master\node_modules\neo-async\async.js:2830:7
    at Object.each (C:\Projects\test\Rust-TypeScript-Wasm-Template-master\node_modules\neo-async\async.js:2850:39)
    at C:\Projects\test\Rust-TypeScript-Wasm-Template-master\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:361:18
    at C:\Projects\test\Rust-TypeScript-Wasm-Template-master\node_modules\neo-async\async.js:2830:7
    at Object.each (C:\Projects\test\Rust-TypeScript-Wasm-Template-master\node_modules\neo-async\async.js:2850:39)
 @ ./node_modules/mocha/browser-entry.js 18:12-34
 @ ./spec/runner.js 1:0-15
```

Am I on the right path?

**Comment by h3nnn4n** [comment]
Hey @ZhaoXiangXML Sorry for the delay to get back to you. Still interested?

I can take a look this next weekend. 

tbh I never tested any of this on windows, only mac / linux, so I can't guaranteed it even works there. With that being said, I had plenty of issues running on mac / linux too. The whole CI is very finicky.

**Comment by ZhaoXiangXML** [comment]
Thank you for your kind reply, however I'm not interested in this issue any more.

I've got my typescript+rust project up and running from another template project: https://github.com/ZhaoXiangXML/threets-rust-wasm-template.

**Comment by h3nnn4n** [comment]
Awesome. Glad you found a solution
